# Build Stage
FROM rust:latest AS build

WORKDIR /usr/src/

# Install musl-tools
RUN apt-get update && apt-get install -y musl-tools

# Copy over your source code
COPY . .

# Compile the Rust application for static linking
RUN rustup target add x86_64-unknown-linux-musl \
    && cargo build --release --target=x86_64-unknown-linux-musl

# Runtime Stage
FROM scratch

# Copy the statically compiled binary from the build stage
COPY --from=build /usr/src/target/x86_64-unknown-linux-musl/release/websokek /

# Execute the binary
CMD ["/websokek"]
